### ISSUE TITLE
Default Apache httpd.conf file has moved

### ISSUE THREAD

**Issue by trinitron79** [vBrit/3-Tier-Apps#1]
for the DB and App the latest versions seem to use the /etc/httpd/conf/httpd.conf as a default location.
Tried this for Photon 4 Rev2 and 5.

root@app-01a [ ~ ]# httpd -V
Server version: Apache/2.4.56 (Unix)
Server built:   Apr 25 2023 01:37:10
Server's Module Magic Number: 20120211:126
Server loaded:  APR 1.7.0, APR-UTIL 1.6.1, PCRE 10.40 2022-04-14
Compiled using: APR 1.7.0, APR-UTIL 1.6.1, PCRE 10.40 2022-04-14
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_PROC_PTHREAD_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/etc/httpd/bin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

Made changes to: 
playbooks/roles/db/tasks/configure.yml 
```
- name: Remove Old httpd.conf in /etc/httpd/
    ansible.builtin.file:
      path: /etc/httpd/conf/httpd.conf
      state: absent

  - name: Copy httpd.conf into /etc/httpd/
    ansible.builtin.copy:
      src: files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
      backup: yes
```

playbooks/roles/app/tasks/configure.yml
```
- name: Copy httpd.conf to /etc/httpd/conf/
  copy:
    src: files/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
```
